### ISSUE TITLE
Error in TreeDetails

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/mathislewald#23]
TreeDetails page wont load:
`
react-dom.development.js:12056 Uncaught TypeError: Cannot read properties of undefined (reading '0')`

**Comment by JesJehle** [comment]
Ok, fixed the error by providing a making the list optional via `?`.
`getImageData(feature.properties.images?.[0]).then((data) =>`

**Comment by JesJehle** [comment]
Ok, at it looks like, the image are not loaded:
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/23353378/224686058-6da086c0-fad8-4e12-8a3e-dd04cb2697aa.png">

**Comment by mmaelicke** [comment]
I did some changes to the data-model. Maybe you need to remove the indexDB and refresh the page. The offline storage is only updated, when the remote data checksums change. Here, I am working on the code, not the remote data, thus, during development, the offline storage needs to be refreshed by hand (remove and reload).

**Comment by JesJehle** [comment]
Great works!
