### ISSUE TITLE
Update Layout

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/mathislewald#7]
Just some first planning:
- [x] Move Background map selection to a separate Popover, which is triggered by a button on the map.
     Consisting of layer selection with checkboxes and a description of the selected layer.
     This way, layer selection is only available while the user is engaged with the map.
- [x] Add filter and data description part to the `DataLayerDrawer` 
- [x] The toggle between map and list view is implemented with `tabs`, not with the bottom sheet modal.
     For mobile, normal tabs can be used, as already developed.
     For desktop, I move the tabs to the top and add titles to the icons. List or maps covers the screen.

- [x] Restructure `TreeDetails` in different sections, use short titles for segments and display long titles below.

**Comment by mmaelicke** [comment]
sounds good to me. The only thing we need to be careful with is the `filter` part, as that is also influenced by the work I am doing on the Offline part. 
That needs to be discussed, before implementing

**Comment by JesJehle** [comment]
Yes, I will only implement the visual components without functionality.
