### ISSUE TITLE
Filter is deselected sometimes

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/mathislewald#71]
After initializing, the all range filters are deselected, most of the time.
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/23353378/231383661-db3e9f14-2f4a-42cb-bfa4-76453ce41b10.png">

**Comment by mmaelicke** [comment]
The range filter now deactivates itself, if not all necessary base-data is available (ie. the min and max values).
I will check the logic, I seem to have missed something...

**Comment by JesJehle** [comment]
Fixed the error in branch #73. 
Vor `height` changed passing value from `value={height}` to 
```
value={{
            lower: height?.lower!,
            upper: height?.upper!,
          }}
```
for radius multiplied value by 100 🤕

**Comment by JesJehle** [comment]
Ok, as soon as I closed the inspector, the filter doesn't work anymore.

**Comment by mmaelicke** [comment]
OK, I guess then there is something wrong with the component lifecycle as using the inspector and console.log stuff always slows the app down. I'll have a look
